version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.0
  pre_build:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet publish -c release
artifacts:
  files:
    - '**/*'
