version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./buildoutput
      - cp -rf scripts buildoutput/scripts
      - cp appspec.yml buildoutput/appspec.yml
artifacts:
  files:
    - '**/*'
  base-directory: buildoutput
